<?php /** @var \Artisangora\Task\Block\Index $block */ ?>

<h1>Task Dashboard</h1>

<table>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
    </tr>

    <?php foreach ($this->getTasks() as $task) : ?>
        <tr>
            <td> <?php echo $task->getId(); ?></td>
            <td> <?php echo $task->getTitle(); ?></td>
            <td> <?php echo $task->getContent() ?? '-'; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
